# config/routes/attributes.yaml
controllers:
    resource:
        path: ../../src/Infrastructure/Delivery/API
        namespace: App\Infrastructure
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute